# Generated by Django 4.2.2 on 2023-06-09 13:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('is_edit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WordMeaning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meaning', models.TextField()),
                ('example', models.TextField()),
                ('synonyms', models.TextField()),
                ('priority', models.IntegerField(null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.word')),
            ],
        ),
    ]
