# Generated by Django 4.2.2 on 2023-06-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordmeaning',
            name='example',
        ),
        migrations.RemoveField(
            model_name='wordmeaning',
            name='synonyms',
        ),
    ]
