# Generated by Django 4.2.2 on 2023-06-08 12:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_meaning_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordMeaning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meaning', models.TextField(max_length=255)),
                ('priority', models.IntegerField(null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.word')),
            ],
        ),
        migrations.DeleteModel(
            name='Meaning',
        ),
    ]
