# Generated by Django 4.2.2 on 2023-06-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_wordmeaning_delete_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
    ]
